### ISSUE TITLE
Freeing read locks ...

### ISSUE THREAD

**Issue by remicollet** [remicollet/rpminfo#2]
From @SteenSchutt:

Looks good to me. I can't seem to provoke any more errors from version comparisons with the data I have.

On a completely different note, test 007 has started failing. When I copy out the two lines of code and execute the php script on its own, I'm getting the following:
```
BDB2053 Freeing read locks for locker 0x9837: 113373/139658202564736
BDB2053 Freeing read locks for locker 0x9838: 113373/139658202564736
BDB2053 Freeing read locks for locker 0x9839: 113373/139658202564736
bool(false)
array(1) {
  [0]=>
  array(5) {
    ["Name"]=>
    string(4) "bash"
    ["Version"]=>
    string(6) "4.2.46"
    ["Release"]=>
    string(6) "33.el7"
    ["Summary"]=>
    string(26) "The GNU Bourne Again shell"
    ["Arch"]=>
    string(6) "x86_64"
  }
}
```

I imagine the top three lines are causing the failure. I don't know if there's a way to deal with that. They appear somewhat sporadically, but I'm not aware of anything touching rpmdb on the host.

After having run `php -r 'var_dump(rpmdbinfo("doesntexistsinrpmdb"));'` once, the warnings don't appear the next time, but after calling it on bash they seem to start appearing again. Here's a terminal dump of the behaviour: https://pastebin.com/EhDRyFkg

Everything points to PHP being the process causing the problem.

**Comment by remicollet** [comment]
@SteenSchutt: can you please test if 9bae085b0ed5779eb1daeca8f8eb4e77a32aeab6 solves this ?

**Comment by SteenSchutt** [comment]
> @SteenSchutt: can you please test if [9bae085](https://github.com/remicollet/rpminfo/commit/9bae085b0ed5779eb1daeca8f8eb4e77a32aeab6) solves this ?

Seems to still be happening with a fresh pull from master

**Comment by remicollet** [comment]
I was able to reproduce on a RHEL-7 VM

Really fixed by 5d618874e6c97d9adea540220373ce906914e6a9  and  cf24cad61566ea38ad11526d9111b40861a2ccfa

**Comment by SteenSchutt** [comment]
Can confirm that it works now :+1:

**Comment by remicollet** [comment]
great!   \o/

**Comment by SteenSchutt** [comment]
Do you have a make target for deinstall, or is there a simple way for me to remove the manually compiled version? It's on a test box, but just wondering if I can clean it up a bit.

**Comment by remicollet** [comment]
Sorry, no uninstal target (from upstream php build system)

**Comment by remicollet** [comment]
**Version 0.2.3** released (and RPM in my repository, as usually).
